name: ci

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  test-and-publish:
    name: Build, test and publish
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.3.1
      with:
        minikube version: 'v1.12.3'
        kubernetes version: 'v1.16.4'
        driver: 'docker'
        github token: ${{ github.token }}

    - name: Test
      run: |
        ./test/run_scaling_tests.sh

    - name: Publish
      if: github.ref == 'refs/heads/main'
      env:
        USERNAME: ${{ github.actor }}
        PASSWORD: ${{ github.token }}
        REPO: ${{ github.repository }}
      run: |
        ./bin/push_docker_image.sh

    - name: Update image tag in cwm-worker-deployment-minio/helm/values.yaml
      if: github.ref == 'refs/heads/main'
      env:
        DEPLOY_KEY: ${{ secrets.CWM_WORKER_MINIO_DEPLOY_KEY }}
      run: |
        ./bin/update_minio_image_tag.sh
