name: ci

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  ci:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    # - name: Setup Minikube
    #   uses: manusa/actions-setup-minikube@v2.10.0
    #   with:
    #     minikube version: 'v1.32.0'
    #     kubernetes version: 'v1.29.0'
    #     driver: 'docker'
    #     github token: ${{ secrets.GITHUB_TOKEN }}

    - name: Start minikube
      run: |
        minikube version
        minikube start

    - name: Test
      run: |
        ./test/run_scaling_tests.sh

    - name: Publish
      if: github.ref == 'refs/heads/main'
      env:
        USERNAME: ${{ github.actor }}
        PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
      run: |
        ./bin/push_docker_image.sh

    # - name: Update image tag in cwm-worker-deployment-minio/helm/values.yaml
    #   if: github.ref == 'refs/heads/main'
    #   env:
    #     DEPLOY_KEY: ${{ secrets.CWM_WORKER_MINIO_DEPLOY_KEY }}
    #   run: |
    #     ./bin/update_minio_image_tag.sh
